on: [push, pull_request]

name: Autotools CI

env:
  DESTDIR: "${{ github.workspace }}/dist/"

jobs:
  "Package_Source":
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0

    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      run: |
        sudo apt-get install \
          build-essential \
          automake \
          autoconf-archive \
          binutils-dev \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxml2-dev \
          libfreetype6-dev \
          libpng-dev \
          libopenal-dev \
          libvorbis-dev \
          libiberty-dev \
          gettext \
          autopoint \
          intltool

    - name: Autotools Setup
      id: setup
      run: |
        sh autogen.sh
        sh configure
      working-directory: "source"

    - name: Autotools Dist
      id: compile
      run: |
        make dist-gzip
      working-directory: "source"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: naev-autotools-dist-${{ github.sha }}
        path: ${{ github.workspace }}/source/naev-*.tar.gz
        if-no-files-found: error

  "Compile_Naev":
    needs: "Package_Source"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-16.04
            shell: bash
            config: linux.ini
            pkg-config-path: "[]"

          - os: ubuntu-18.04
            shell: bash
            config: linux.ini
            pkg-config-path: "[]"

          - os: ubuntu-20.04
            shell: bash
            config: linux.ini
            pkg-config-path: "[]"

          - os: windows-2016
            shell: msys2 {0}
            config: windows.ini
            pkg-config-path: "[]"

          - os: windows-2019
            shell: msys2 {0}
            config: windows.ini
            pkg-config-path: "[]"

    defaults:
      run:
        shell: ${{ matrix.shell }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Update APT Cache
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get install \
          build-essential \
          automake \
          autoconf-archive \
          binutils-dev \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxml2-dev \
          libfreetype6-dev \
          libpng-dev \
          libopenal-dev \
          libvorbis-dev \
          libiberty-dev \
          gettext \
          autopoint \
          intltool

    - name: Install MinGW Packages
      if: ${{ runner.os == 'Windows'}}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        path-type: strict
        install: mingw-w64-x86_64-libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libpng mingw-w64-x86_64-openal mingw-w64-x86_64-libvorbis mingw-w64-x86_64-binutils mingw-w64-x86_64-freetype mingw-w64-x86_64-gettext mingw-w64-x86_64-luajit mingw-w64-x86_64-pkg-config libtool autoconf autoconf-archive automake automake-wrapper git gettext pkg-config make intltool itstool

    - name: Get Source
      uses: actions/download-artifact@v2
      with:
        name: naev-autotools-dist-${{ github.sha }}

    - name: Extract Source
      run: |
        mkdir source
        tar -xf naev-*.tar.gz -C source --strip 1

    - name: Autotools Setup
      id: setup
      run: |
        sh autogen.sh
        sh configure
      working-directory: "source"

    - name: Autotools Compile
      id: compile
      run: |
        make -j"$(nproc)"
      working-directory: "source"

    - name: Package
      run: |
        make install
        tar -cvf naev-${{ matrix.os }}-autotools-${{ github.sha }}.tar dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: naev-${{ matrix.os }}-autotools-${{ github.sha }}
        path: ${{ github.workspace }}/*.tar
        if-no-files-found: error
