on: [push, pull_request]

name: AppImage CI

env:
  DESTDIR: "${{ github.workspace }}/dist/"
  MESON: "${{ github.workspace }}/source/meson.sh"

jobs:
  "Package_Source":
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Naev Repository
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0

    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      run: |
        sudo apt-get install \
          ninja-build

    - name: Meson Build
      run: |
        sh $MESON setup build source -Dexecutable=disabled -Ddocs_c=disabled -Ddocs_lua=disabled
        sh $MESON dist -C build --no-tests --include-subprojects

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: naev-meson-dist-${{ github.sha }}
        path: ${{ github.workspace }}/build/meson-dist/*
        if-no-files-found: error

  "Compile_AppImage":
    needs: "Package_Source"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-16.04
            shell: bash
            config: linux.ini
            pkg-config-path: "[]"

    defaults:
      run:
        shell: ${{ matrix.shell }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Update APT Cache
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get update

    - name: Install Additional Build Dependencies
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get install \
          autopoint \
          binutils-dev \
          build-essential \
          gettext \
          intltool \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libiberty-dev \
          libluajit-5.1-dev \
          libopenal-dev \
          libpng-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsuitesparse-dev \
          libvorbis-dev \
          libxml2-dev

    - name: Install Ninja-Build (xenial-backports)
      if: ${{ matrix.os == 'ubuntu-16.04' && runner.os == 'Linux'}}
      run: |
        sudo apt-get -t xenial-backports install \
          ninja-build

    - name: Install Ninja-Build
      if: ${{ matrix.os != 'ubuntu-16.04' && runner.os == 'Linux'}}
      run: |
        sudo apt-get install \
          ninja-build

    - name: Get Source
      uses: actions/download-artifact@v2
      with:
        name: naev-${{ github.sha }}

    - name: Extract Source
      run: |
        mkdir source
        tar -xf naev-*.tar.xz -C source --strip 1

    - name: Compile AppImage
      id: compile
      run: |
        sh source/utils/buildAppImage.sh -s "source" -b "build" -o "${{ env.DESTDIR }}" |& tee -a appImageBuildLog.txt

    - name: Upload Compile Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || steps.compile.outcome == 'failure' }}
      with:
        name: ${{ matrix.os }}-${{ github.sha }}-appimageBuild-log
        path: ${{ github.workspace }}/appImageBuildLog.txt
        if-no-files-found: ignore

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: naev-${{ matrix.os }}-AppImage-${{ github.sha }}
        path: ${{ env.DESTDIR }}/out/*.AppImage
        if-no-files-found: error
